### PR TITLE
Create CONTRIBUTING.md for the Plone GitHub organization

### PR DESCRIPTION
**Pull request by stevepiercy**

### CODE REVIEW

**Review by mauritsvanrees — APPROVED** [review]
I will merge. Let's see how it looks.

**Comment by mauritsvanrees** [comment]
I don't see the new text anywhere.

**Comment by stevepiercy** [comment]
This might be for new contributors only. Here's what I see when I click New Issue in this repo.

Screen Shot 2022-08-18 at 6 14 12 PM

...and that message has a link to:

https://github.com/plone/.github/blob/28dcda76d05a4972f1f7f56ca8ead16ac763ad33/CONTRIBUTING.md

Try finding a repo to which you have not contributed and see if it shows up.

Also this CONTRIBUTING.md is used only when a repo does not already have one. Thus individual repos can override the organization CONTRIBUTING.md.

It occurred to me that we might want to add a link and an explanation of what is Plone Core:

https://docs.plone.org/develop/coredev/docs/index.html

**Comment by mauritsvanrees** [comment]
Ah, right, I did not now where to look, I was looking in the root of the repository only.

**Comment by stevepiercy** [comment]
Yup. This repo is meta to the Plone organization.

**Pull request merged**
